name: CD — Deploy to EC2

on:
  push:
    branches: [main]

jobs:
  deploy:
    runs-on: ubuntu-latest
    needs: []   # Remove this line if you want to require CI to pass first

    steps:
      - name: Deploy to EC2 via SSH
        uses: appleboy/ssh-action@v1
        with:
          host:     ${{ secrets.EC2_HOST }}
          username: ubuntu
          key:      ${{ secrets.EC2_SSH_KEY }}
          script: |
            sudo apt update && sudo apt install -y docker.io docker-compose-plugin
            sudo usermod -aG docker ubuntu
            if [ ! -d "~/devops-project" ]; then
              git clone https://github.com/Syed-Shaheryar-Shah-2212200/2212200-devops-project ~/devops-project
            fi
            cd ~/devops-project
            git pull origin main
            echo "DB_USER=devops_user" > .env.production
            echo "DB_PASSWORD=devops_pass_2212200_prod" >> .env.production
            echo "DB_NAME=devops_db_prod" >> .env.production
            cp .env.production .env
            sudo docker compose -f docker-compose.prod.yml down
            sudo docker compose -f docker-compose.prod.yml up -d --build
            echo "Deployed at $(date)"
